services:
  filelink:
    # build: ..
    image: smartworldarafath/filelink
    container_name: filelink-app
    environment:
      - SECRET_KEY=<SECRET_KEY>
    ports:
      - "80:80"
    depends_on:
      - coturn
    restart: unless-stopped

  coturn:
    image: coturn/coturn:alpine
    container_name: filelink-coturn
    command:
      - --fingerprint
      - --use-auth-secret
      - --no-multicast-peers
      - --no-cli
      - --realm=filelink.app
      - --static-auth-secret=<SECRET_KEY>
      - --listening-port=3478
      - --min-port=50000
      - --max-port=50100
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "50000-50100:50000-50100/udp"
    restart: unless-stopped